var HOME_NET any
var EXTERNAL_NET any
config detection: search-method ac-bnfa
config checksum_mode: none
# config event_queue: max_queue 20 log 20 order_events content_length
preprocessor frag3_global
preprocessor frag3_engine: policy windows
preprocessor stream5_global: track_tcp yes, track_udp yes
preprocessor stream5_tcp: policy windows, ports both 80 8080 5985
preprocessor stream5_udp
preprocessor http_inspect: global iis_unicode_map /etc/snort/unicode.map 1252
preprocessor http_inspect_server: server default profile all ports { 80 8080 5985 } extended_response_inspection inspect_gzip
include RULEFILE
